version: '3.4'

services:
  testnet-node:
    container_name: testnet-node
    build: ../..
    image: kardiachain/go-kardia
    ports:
      - 3000:3000
      - 3000:3000/udp
      - 8545:8545
    volumes:
      - ./genesis_testnet.yaml:/go/bin/genesis_testnet.yaml
      - ./node_testnet.yaml:/go/bin/node_testnet.yaml
      - .:/root/.kardia
    command: [ 
      "--genesis", "genesis_testnet.yaml",
      "--network", "testnet",
      "--node","node_testnet.yaml" ]
    logging:
      driver: "json-file"
      options:
        max-size: 300m