# .goreleaser.yml
builds:
  # You can have multiple builds defined as a yaml list
  - # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
