version: '3.4'

services:
  mainnet-node:
    container_name: kai-mainnet-node
    image: gcr.io/indigo-history-235904/go-kardia:stable
    ports:
      - 3000:3000
      - 3000:3000/udp
      - 8545:8545
    volumes:
      - ./kai_config.yaml:/go/bin/kai_config.yaml
      - ./genesis.yaml:/go/bin/cfg/genesis.yaml # mainnet coming soon, so genesis.yaml will be updated
      - .:/root/.kardia
    command: [ "--network", "mainnet", "--node", "kai_config.yaml" ]
    logging:
      driver: "json-file"
      options:
        max-size: 300m