version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-stretch
    working_directory: /go/src/github.com/kardiachain/go-kardia

    environment:
      CODECOV_TOKEN: 7b55d1cf-771a-4787-8f11-c234e1f21ace

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: get dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y libzmq3-dev

      - run:
          name: Run unit test
          command: |
            bash .circleci/test.sh

      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Build
          command: |
            cd cmd
            go build -v

  release:
    docker:
      - image: circleci/golang:1.12-stretch
    working_directory: /go/src/github.com/kardiachain/go-kardia

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: get dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
            
      - run:
          name: Run release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

