Node:
  Name: node1             # node name
  DataDir: /tmp/.kardia   # database data directory
  HTTPHost: 0.0.0.0       # RPC address
  HTTPPort: 8545          # RPC port
  HTTPModules:            # accepted API modules
    - node
    - kai
    - tx
    - account
  HTTPVirtualHosts:       # virtual hosts connection
    - 0.0.0.0
    - 127.0.0.1
    - localhost
  HTTPCors:               # cors, use "*" to accept all
    - 0.0.0.0
    - 127.0.0.1
    - localhost
  P2P:
    PrivateKey:      # private key without 0x prefix, eg: 8843ebcb1021b00ae9a644db6617f9c6d870e5fd53624cefe374c1d2d710fd06
    ListenAddress: tcp://0.0.0.0:3000 # IP and Port for P2P connection
    MaxPeers: 25     # maximum accepted peers
  LogLevel: info     # crit, error, warn, info, debug, trace
  Metrics: 1
MainChain:
  ServiceName: KARDIA #
  ChainId: 1          # 1 = Mainnet, 10 = Testnet
  NetworkId: 100      # 100 = Mainnet, 1000 = Testnet
  AcceptTxs: 1        # accept tx sync process or not (1 is yes, 0 is no)
  Seeds:
    - c1fe56e3f58d3244f606306611a5d10c8333f1f6@127.0.0.1:3000
    - 7cefc13b6e2aedeedfb7cb6c32457240746baee5@127.0.0.1:3001
    - ff3dac4f04ddbd24de5d6039f90596f0a8bb08fd@127.0.0.1:3002
  Database:
    Dir: chaindata                           # directory stores leveldb
    Cache: 16                                # cache is used in leveldb
    Handles: 32                              # handles is used in leveldb
    Drop: 1                                  # Specify whether drop database or not (0 is no, 1 is yes)
Debug:
  Port: ":6000"