RPCList:
  - http://172.20.0.5:8547
Database:
  uri: mongodb://172.20.0.6:27017
  db: kardiachain
Application:
  windowSize: 200
  blockInterval: 10
  handleBlockInterval: 2
  requestBlockSize: 20
  handleBlockSize: 100
  handleTxInterval: 5
  handleTxSize: 200
  apiPort: 8000